name: (📡) Verify

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: pnpm verify

      - name: Upload to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage/cobertura-coverage.xml
          verbose: true
